"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from pydantic import ValidationError

from config.env import Environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ADR-0001 section 4: configuration comes from the environment. The SECRET_KEY that
# `startproject` wrote into this file was removed before the first commit.
try:
    env = Environment()
except ValidationError as error:
    # Anything that loads Django surfaces this, and django-stubs surfaces it as
    # `INTERNAL ERROR -- Error constructing plugin instance`, which tells a newcomer nothing.
    raise ImproperlyConfigured(
        "The API environment is incomplete or invalid.\n"
        "Copy apps/api/.env.example to apps/api/.env and fill it in, or export the variables.\n"
        "This is required by anything that loads Django here, which includes manage.py, the "
        "type checker and the test suite.\n\n"
        f"{error}"
    ) from error

SECRET_KEY = env.secret_key.get_secret_value()

DEBUG = env.debug

ALLOWED_HOSTS = env.allowed_hosts


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # It loads GDAL and GEOS at import, which is why it waited for the first geometry model and
    # why it runs in the container (specs/dependencies.md section 1, ADR-0001 section 3).
    "django.contrib.gis",
    "mapsift.accounts",
    "mapsift.layers",
    "mapsift.sync",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        **env.django_database(),
        # PostGIS is not a `trusted` extension, and this connection is deliberately not a
        # superuser (ADR-0005 section 2), so the test database has to be copied from a template
        # that already carries it rather than installing it on creation.
        "TEST": {"TEMPLATE": "template_postgis"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
