# Generated by Django 5.2.16 on 2026-08-04 23:13
#
# The layer and the feature of M2, put inside the isolation wall of ADR-0005 section 7 in the same
# migration that creates them, with geometry in the one frame of M5 rule 1.
#
# The tables come from the autodetector; what follows is what it cannot express. Each cites the
# decision it comes from rather than repeating why that decision was taken.

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

# ADR-0005 section 7, which names both of these among the tables inside the wall.
TENANT_OWNED_TABLES = (
    "layers_layer",
    "layers_feature",
)

# The `nullif` is not cosmetic and the bare cast is a defect, measured rather than argued
# (ADR-0005 section 3, measurement C).
TENANT_IN_FORCE = "nullif(current_setting('mapsift.tenant_id', true), '')::uuid"

ENABLE_THE_WALL = "\n".join(
    f"""
    ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
    ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
    CREATE POLICY tenant_isolation ON {table}
        USING (tenant_id = {TENANT_IN_FORCE})
        WITH CHECK (tenant_id = {TENANT_IN_FORCE});
    """
    for table in TENANT_OWNED_TABLES
)

DISABLE_THE_WALL = "\n".join(
    f"""
    DROP POLICY tenant_isolation ON {table};
    ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;
    ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
    """
    for table in TENANT_OWNED_TABLES
)

# ADR-0005 section 2. `mapsift_tile` is deliberately granted nothing: it is the direct-to-PostGIS
# reader, its path is an open ADR, and ADR-0001 section 8 forbids scaffolding an untaken decision.
GRANT_THE_APPLICATION_ITS_TABLES = f"""
    GRANT SELECT, INSERT, UPDATE, DELETE
        ON {", ".join(TENANT_OWNED_TABLES)}
        TO mapsift_app;
"""

REVOKE_THE_APPLICATION_ITS_TABLES = f"""
    REVOKE ALL ON {", ".join(TENANT_OWNED_TABLES)} FROM mapsift_app;
"""

# ADR-0005 section 5, and the reason both models carry db_constraint=False. The feature's reference
# is three columns rather than two: the tenant channel is what the composite closes, and the
# project column is what keeps a feature from resolving to its own project and its layer's (M2).
ADD_THE_COMPOSITE_REFERENCES = """
    ALTER TABLE layers_layer
        ADD CONSTRAINT layer_project_within_the_same_tenant
        FOREIGN KEY (tenant_id, project_id)
        REFERENCES accounts_project (tenant_id, id);

    ALTER TABLE layers_feature
        ADD CONSTRAINT feature_layer_within_the_same_tenant_and_project
        FOREIGN KEY (tenant_id, project_id, layer_id)
        REFERENCES layers_layer (tenant_id, project_id, id);
"""

DROP_THE_COMPOSITE_REFERENCES = """
    ALTER TABLE layers_feature DROP CONSTRAINT feature_layer_within_the_same_tenant_and_project;
    ALTER TABLE layers_layer DROP CONSTRAINT layer_project_within_the_same_tenant;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_project_project_identity_within_its_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('geometry_kind', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], max_length=32)),
                ('storage_class', models.CharField(choices=[('element', 'Element'), ('served', 'Served')], max_length=32)),
                ('project', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='accounts.project')),
                ('tenant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4674)),
                ('project', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='accounts.project')),
                ('tenant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='accounts.tenant')),
                ('layer', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='layers.layer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'id'), name='layer_identity_within_its_tenant_and_project'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['tenant', 'layer'], name='feature_layer_by_tenant'),
        ),
        migrations.RunSQL(
            sql=GRANT_THE_APPLICATION_ITS_TABLES,
            reverse_sql=REVOKE_THE_APPLICATION_ITS_TABLES,
        ),
        migrations.RunSQL(sql=ENABLE_THE_WALL, reverse_sql=DISABLE_THE_WALL),
        # After the AddConstraint above, which is the unique key the second reference points at.
        migrations.RunSQL(
            sql=ADD_THE_COMPOSITE_REFERENCES,
            reverse_sql=DROP_THE_COMPOSITE_REFERENCES,
        ),
    ]
