# Generated by Django 5.2.16 on 2026-08-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membership_membership_by_user_for_login"),
        ("layers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["tenant", "project"], name="feature_project_by_tenant"
            ),
        ),
    ]
