# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class FeatureCreatePayload(BaseModel):
    pass


class FeatureGeometrySetPayload(BaseModel):
    geometry: Annotated[
        Any,
        Field(
            description="A GeoJSON-shaped structure in the M5 storage frame. Opaque to the core until the boundary\nencoding is decided (MAP-33)."
        ),
    ]


class FeatureAddress(BaseModel):
    feature_id: UUID
    kind: Literal["feature"]
    layer_id: UUID
    project_id: UUID
    tenant_id: UUID


class FeatureTarget(RootModel[FeatureAddress]):
    root: Annotated[
        FeatureAddress,
        Field(
            description="A whole-feature address, carrying its ancestors so it resolves without a lookup (M9)."
        ),
    ]


class MediationProvenance(BaseModel):
    agent: str


class PropertyAddress(BaseModel):
    feature_id: UUID
    kind: Literal["property"]
    layer_id: UUID
    project_id: UUID
    property: str
    tenant_id: UUID


class PropertyTarget(RootModel[PropertyAddress]):
    root: Annotated[
        PropertyAddress,
        Field(
            description="One property of one feature, the finest granularity the ladder measures a conflict on (M9)."
        ),
    ]


class Verdict(StrEnum):
    applied = "applied"


class FeatureCreateOperation(BaseModel):
    author_session_material: Annotated[
        Any,
        Field(
            description="Opaque to the core: the proof mechanism is OQ-18's and the server is what verifies it."
        ),
    ]
    client_id: UUID
    conflict_rule_version: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    mediation: MediationProvenance | None
    mutation_number: Annotated[
        int,
        Field(
            description="The per-client monotonic axis the server dedups a resent flush by (C12).",
            ge=0,
        ),
    ]
    operation_id: UUID
    operation_schema_version: Annotated[int, Field(ge=0)]
    operation_type: Literal["feature.create"]
    payload: FeatureCreatePayload
    target: FeatureTarget


class FeatureGeometrySetOperation(BaseModel):
    author_session_material: Annotated[
        Any,
        Field(
            description="Opaque to the core: the proof mechanism is OQ-18's and the server is what verifies it."
        ),
    ]
    client_id: UUID
    conflict_rule_version: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    mediation: MediationProvenance | None
    mutation_number: Annotated[
        int,
        Field(
            description="The per-client monotonic axis the server dedups a resent flush by (C12).",
            ge=0,
        ),
    ]
    operation_id: UUID
    operation_schema_version: Annotated[int, Field(ge=0)]
    operation_type: Literal["feature.geometry.set"]
    payload: FeatureGeometrySetPayload
    target: PropertyTarget


class ClientHalf(RootModel[FeatureCreateOperation | FeatureGeometrySetOperation]):
    root: Annotated[
        FeatureCreateOperation | FeatureGeometrySetOperation,
        Field(
            description="An operation as the client authored it. Every field here is the client's claim; nothing in it\nis authoritative until the server half exists beside it.",
            discriminator="operation_type",
        ),
    ]


class ServerHalf(BaseModel):
    applied_at: AwareDatetime
    applied_rule_version: Annotated[int, Field(ge=0)]
    feature_version: Annotated[
        int,
        Field(
            description="The per-feature axis that orders and detects conflict on one feature (M10).",
            ge=0,
        ),
    ]
    legal_weight_in_force: bool
    verdict: Verdict


class AppliedOperation(BaseModel):
    client: ClientHalf
    server: ServerHalf
