# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class MediationProvenance(BaseModel):
    agent: str


class TenantTarget(BaseModel):
    kind: Literal["tenant"]
    tenant_id: UUID


class ProjectTarget(BaseModel):
    kind: Literal["project"]
    project_id: UUID
    tenant_id: UUID


class LayerTarget(BaseModel):
    kind: Literal["layer"]
    layer_id: UUID
    project_id: UUID
    tenant_id: UUID


class FeatureTarget(BaseModel):
    feature_id: UUID
    kind: Literal["feature"]
    layer_id: UUID
    project_id: UUID
    tenant_id: UUID


class PropertyTarget(BaseModel):
    feature_id: UUID
    kind: Literal["property"]
    layer_id: UUID
    project_id: UUID
    property: str
    tenant_id: UUID


class TargetPath(
    RootModel[TenantTarget | ProjectTarget | LayerTarget | FeatureTarget | PropertyTarget]
):
    root: Annotated[
        TenantTarget | ProjectTarget | LayerTarget | FeatureTarget | PropertyTarget,
        Field(
            description="The one address an operation targets, at the granularity the conflict unit is measured on\n(M9). Each variant carries its ancestors, so an address is resolvable without a lookup.",
            discriminator="kind",
        ),
    ]


class Verdict(StrEnum):
    applied = "applied"


class ClientHalf(BaseModel):
    author_session_material: Annotated[
        Any,
        Field(
            description="Opaque to the core: the proof mechanism is OQ-18's and the server is what verifies it."
        ),
    ]
    client_id: UUID
    conflict_rule_version: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    mediation: MediationProvenance | None
    mutation_number: Annotated[int, Field(ge=0)]
    operation_id: UUID
    operation_schema_version: Annotated[int, Field(ge=0)]
    operation_type: str
    payload: Annotated[
        Any,
        Field(
            description="Opaque to the core: the operation type says how to read it, over the catalog M9 owns."
        ),
    ]
    target: TargetPath


class ServerHalf(BaseModel):
    applied_at: AwareDatetime
    applied_rule_version: Annotated[int, Field(ge=0)]
    feature_version: Annotated[int, Field(ge=0)]
    legal_weight_in_force: bool
    verdict: Verdict


class AppliedOperation(BaseModel):
    client: ClientHalf
    server: ServerHalf
