# Generated by Django 5.2.16 on 2026-08-04 16:03
#
# The account tree of M1, with the isolation wall of ADR-0005 section 7 in the same migration that
# creates it, and identifiers per ADR-0006 sections 3 and 4.
#
# The tables come from the autodetector; what follows is what it cannot express. Each cites the
# decision it comes from rather than repeating why that decision was taken.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# ADR-0005 section 7.
TENANT_OWNED_TABLES = (
    "accounts_tenant",
    "accounts_membership",
    "accounts_workspace",
    "accounts_project",
)

# The `nullif` is not cosmetic and the bare cast is a defect, measured rather than argued
# (ADR-0005 section 3, measurement C).
TENANT_IN_FORCE = "nullif(current_setting('mapsift.tenant_id', true), '')::uuid"

ENABLE_THE_WALL = "\n".join(
    f"""
    ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
    ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
    CREATE POLICY tenant_isolation ON {table}
        USING (tenant_id = {TENANT_IN_FORCE})
        WITH CHECK (tenant_id = {TENANT_IN_FORCE});
    """
    for table in TENANT_OWNED_TABLES
)

DISABLE_THE_WALL = "\n".join(
    f"""
    DROP POLICY tenant_isolation ON {table};
    ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;
    ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
    """
    for table in TENANT_OWNED_TABLES
)

# ADR-0005 section 2. Neither LOGIN nor a password is granted here, because a migration is tracked
# in git and a credential is not (N3, C6); deployment gives them theirs. The guard is not
# redundant either: a role is cluster-wide, while this migration runs once per database.
CREATE_THE_RUNTIME_ROLES = """
    DO $$
    DECLARE
        role_name text;
    BEGIN
        FOREACH role_name IN ARRAY ARRAY['mapsift_app', 'mapsift_tile', 'mapsift_tokens'] LOOP
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
                EXECUTE format(
                    'CREATE ROLE %I NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE',
                    role_name
                );
            END IF;
        END LOOP;
    END
    $$;
"""

GRANT_THE_APPLICATION_ITS_TABLES = f"""
    GRANT USAGE ON SCHEMA public TO mapsift_app;
    GRANT SELECT, INSERT, UPDATE, DELETE
        ON accounts_user, {", ".join(TENANT_OWNED_TABLES)}
        TO mapsift_app;
"""

REVOKE_THE_APPLICATION_ITS_TABLES = f"""
    REVOKE ALL ON accounts_user, {", ".join(TENANT_OWNED_TABLES)} FROM mapsift_app;
    REVOKE USAGE ON SCHEMA public FROM mapsift_app;
"""

# ADR-0005 section 5, and the reason the model carries db_constraint=False.
ADD_THE_COMPOSITE_REFERENCE = """
    ALTER TABLE accounts_project
        ADD CONSTRAINT project_workspace_within_the_same_tenant
        FOREIGN KEY (tenant_id, workspace_id)
        REFERENCES accounts_workspace (tenant_id, id);
"""

DROP_THE_COMPOSITE_REFERENCE = """
    ALTER TABLE accounts_project DROP CONSTRAINT project_workspace_within_the_same_tenant;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_column='tenant_id', editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], max_length=32)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.tenant')),
                ('workspace', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=32)),
                ('licence', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=32)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='one_membership_per_user_per_tenant')],
            },
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='workspace_identity_within_its_tenant'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'workspace'], name='project_workspace_by_tenant'),
        ),
        migrations.RunSQL(
            sql=CREATE_THE_RUNTIME_ROLES,
            # Deliberately not the reverse of the statement above: a role is cluster-wide, so
            # dropping it here would reach every other database that still grants to it.
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=GRANT_THE_APPLICATION_ITS_TABLES,
            reverse_sql=REVOKE_THE_APPLICATION_ITS_TABLES,
        ),
        migrations.RunSQL(sql=ENABLE_THE_WALL, reverse_sql=DISABLE_THE_WALL),
        migrations.RunSQL(
            sql=ADD_THE_COMPOSITE_REFERENCE,
            reverse_sql=DROP_THE_COMPOSITE_REFERENCE,
        ),
    ]
