# Generated by Django 5.2.16 on 2026-08-04 23:13
#
# The composite key ADR-0005 section 5 requires of a referenced table, which Workspace already had
# and Project did not. MAP-5's layer is the first reference that needs it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='project_identity_within_its_tenant'),
        ),
    ]
