# Generated by Django 5.2.16 on 2026-08-05 23:40
#
# The wall's single deliberate exception, ADR-0005 section 8: the second policy on membership and
# the index the login question reads through. The index comes from the autodetector; the policy is
# what it cannot express.

from django.db import migrations, models

# The same guarded cast decision 3 requires of the tenant parameter, on the second one, because
# measurement C applies to it identically (ADR-0005 section 8).
SESSION_USER_IN_FORCE = "nullif(current_setting('mapsift.user_id', true), '')::uuid"

ADD_THE_LOGIN_QUESTION = f"""
    CREATE POLICY membership_of_the_session_user ON accounts_membership
        FOR SELECT
        USING (user_id = {SESSION_USER_IN_FORCE});
"""

DROP_THE_LOGIN_QUESTION = """
    DROP POLICY membership_of_the_session_user ON accounts_membership;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project_project_identity_within_its_tenant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='membership_by_user_for_login'),
        ),
        migrations.RunSQL(sql=ADD_THE_LOGIN_QUESTION, reverse_sql=DROP_THE_LOGIN_QUESTION),
    ]
