# Generated by Django 5.2.16 on 2026-08-10 14:43
#
# The append-only operation log of M15, put inside the isolation wall of ADR-0005 section 7 in the
# same migration that creates it, and granted less than every other tenant-owned table.
#
# The table comes from the autodetector; what follows is what it cannot express. Each cites the
# decision it comes from rather than repeating why that decision was taken.

import django.db.models.deletion
import uuid
from django.db import migrations, models

# ADR-0005 section 7.
OPERATION_LOG = "sync_operationlogentry"

# The `nullif` is not cosmetic and the bare cast is a defect, measured rather than argued
# (ADR-0005 section 3, measurement C).
TENANT_IN_FORCE = "nullif(current_setting('mapsift.tenant_id', true), '')::uuid"

ENABLE_THE_WALL = f"""
    ALTER TABLE {OPERATION_LOG} ENABLE ROW LEVEL SECURITY;
    ALTER TABLE {OPERATION_LOG} FORCE ROW LEVEL SECURITY;
    CREATE POLICY tenant_isolation ON {OPERATION_LOG}
        USING (tenant_id = {TENANT_IN_FORCE})
        WITH CHECK (tenant_id = {TENANT_IN_FORCE});
"""

DISABLE_THE_WALL = f"""
    DROP POLICY tenant_isolation ON {OPERATION_LOG};
    ALTER TABLE {OPERATION_LOG} NO FORCE ROW LEVEL SECURITY;
    ALTER TABLE {OPERATION_LOG} DISABLE ROW LEVEL SECURITY;
"""

# ADR-0005 section 2, addition of 2026-08-07. TRUNCATE is absent from both statements because it
# is never granted rather than revoked, and a REVOKE naming it would read as the thing that closed
# it.
GRANT_THE_APPLICATION_ITS_APPEND = f"""
    GRANT SELECT, INSERT ON {OPERATION_LOG} TO mapsift_app;
"""

REVOKE_THE_APPLICATION_ITS_APPEND = f"""
    REVOKE ALL ON {OPERATION_LOG} FROM mapsift_app;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_membership_membership_by_user_for_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation_id", models.UUIDField()),
                ("client_half", models.JSONField()),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_log_entries",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "operation_id"),
                        name="one_entry_per_operation_within_its_tenant",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=GRANT_THE_APPLICATION_ITS_APPEND,
            reverse_sql=REVOKE_THE_APPLICATION_ITS_APPEND,
        ),
        migrations.RunSQL(sql=ENABLE_THE_WALL, reverse_sql=DISABLE_THE_WALL),
    ]
