# Generated by Django 5.2.16 on 2026-08-10 19:10
#
# The ordering key of ADR-0004 decision 4: the counter a flush allocates its range from, and the
# two columns that carry the result beside the log entry. The counter joins the wall of ADR-0005
# section 7 in the same migration that creates it, and takes the grant of section 2's addition of
# 2026-08-10, which is the log's opposite because its normal operation is an in-place increment.
#
# The table comes from the autodetector with one edit: the tenant reference is inlined into
# CreateModel, because the split the autodetector wrote leaves the composite primary key naming a
# field that does not exist yet and the migration cannot be loaded at all. What follows the model
# is what the autodetector cannot express, each citing the decision it comes from.

import django.db.models.deletion
import uuid
from django.db import migrations, models

# ADR-0005 section 7.
VERSION_COUNTER = "sync_projectversioncounter"

# The `nullif` is not cosmetic and the bare cast is a defect, measured rather than argued
# (ADR-0005 section 3, measurement C).
TENANT_IN_FORCE = "nullif(current_setting('mapsift.tenant_id', true), '')::uuid"

ENABLE_THE_WALL = f"""
    ALTER TABLE {VERSION_COUNTER} ENABLE ROW LEVEL SECURITY;
    ALTER TABLE {VERSION_COUNTER} FORCE ROW LEVEL SECURITY;
    CREATE POLICY tenant_isolation ON {VERSION_COUNTER}
        USING (tenant_id = {TENANT_IN_FORCE})
        WITH CHECK (tenant_id = {TENANT_IN_FORCE});
"""

DISABLE_THE_WALL = f"""
    DROP POLICY tenant_isolation ON {VERSION_COUNTER};
    ALTER TABLE {VERSION_COUNTER} NO FORCE ROW LEVEL SECURITY;
    ALTER TABLE {VERSION_COUNTER} DISABLE ROW LEVEL SECURITY;
"""

# ADR-0005 section 2, addition of 2026-08-10. UPDATE is the one that separates this table from the
# log beside it, and anything narrower stops a flush from running at all.
GRANT_THE_APPLICATION_ITS_ALLOCATION = f"""
    GRANT SELECT, INSERT, UPDATE ON {VERSION_COUNTER} TO mapsift_app;
"""

REVOKE_THE_APPLICATION_ITS_ALLOCATION = f"""
    REVOKE ALL ON {VERSION_COUNTER} FROM mapsift_app;
"""

# ADR-0004 decision 2's second supporting rule: the one row per project this strategy accepts as
# hot is where bloat starts, so the cluster default (vacuum at a fifth of a table this small, which
# is never) is the wrong policy here and nowhere else in this schema.
TUNE_AUTOVACUUM_FOR_ONE_HOT_ROW_PER_PROJECT = f"""
    ALTER TABLE {VERSION_COUNTER} SET (
        autovacuum_vacuum_scale_factor = 0.0,
        autovacuum_vacuum_threshold = 50
    );
"""

RESTORE_THE_CLUSTER_DEFAULT = f"""
    ALTER TABLE {VERSION_COUNTER} RESET (
        autovacuum_vacuum_scale_factor,
        autovacuum_vacuum_threshold
    );
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membership_membership_by_user_for_login"),
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectVersionCounter",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "tenant",
                        "project_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_version_counters",
                        to="accounts.tenant",
                    ),
                ),
                ("project_id", models.UUIDField()),
                ("version", models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="operationlogentry",
            name="project_id",
            field=models.UUIDField(
                default=uuid.UUID("00000000-0000-0000-0000-000000000000")
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operationlogentry",
            name="project_version",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="operationlogentry",
            index=models.Index(
                fields=["tenant", "project_id", "project_version"],
                name="log_by_project_version",
            ),
        ),
        migrations.RunSQL(
            sql=GRANT_THE_APPLICATION_ITS_ALLOCATION,
            reverse_sql=REVOKE_THE_APPLICATION_ITS_ALLOCATION,
        ),
        migrations.RunSQL(sql=ENABLE_THE_WALL, reverse_sql=DISABLE_THE_WALL),
        migrations.RunSQL(
            sql=TUNE_AUTOVACUUM_FOR_ONE_HOT_ROW_PER_PROJECT,
            reverse_sql=RESTORE_THE_CLUSTER_DEFAULT,
        ),
    ]
