# Generated by Django 5.2.16 on 2026-08-11 19:04
#
# The per-client cursor of PRD M4, keyed by clientID, tenant and project together, put inside the
# isolation wall of ADR-0005 section 7 in the same migration that creates it and granted the set
# its own guarantee needs.
#
# The table comes from the autodetector; what follows the model is what it cannot express, each
# citing the decision it comes from.

import django.db.models.deletion
from django.db import migrations, models

# ADR-0005 section 7.
CLIENT_CURSOR = "sync_clientcursor"

# The `nullif` is not cosmetic and the bare cast is a defect, measured rather than argued
# (ADR-0005 section 3, measurement C).
TENANT_IN_FORCE = "nullif(current_setting('mapsift.tenant_id', true), '')::uuid"

ENABLE_THE_WALL = f"""
    ALTER TABLE {CLIENT_CURSOR} ENABLE ROW LEVEL SECURITY;
    ALTER TABLE {CLIENT_CURSOR} FORCE ROW LEVEL SECURITY;
    CREATE POLICY tenant_isolation ON {CLIENT_CURSOR}
        USING (tenant_id = {TENANT_IN_FORCE})
        WITH CHECK (tenant_id = {TENANT_IN_FORCE});
"""

DISABLE_THE_WALL = f"""
    DROP POLICY tenant_isolation ON {CLIENT_CURSOR};
    ALTER TABLE {CLIENT_CURSOR} NO FORCE ROW LEVEL SECURITY;
    ALTER TABLE {CLIENT_CURSOR} DISABLE ROW LEVEL SECURITY;
"""

# ADR-0005 section 2, addition of 2026-08-10, which fixes the grant per table by what that table
# guarantees. This one advances in place like the version counter beside it, so it takes UPDATE.
GRANT_THE_APPLICATION_ITS_ADVANCE = f"""
    GRANT SELECT, INSERT, UPDATE ON {CLIENT_CURSOR} TO mapsift_app;
"""

REVOKE_THE_APPLICATION_ITS_ADVANCE = f"""
    REVOKE ALL ON {CLIENT_CURSOR} FROM mapsift_app;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membership_membership_by_user_for_login"),
        ("sync", "0002_projectversioncounter_operationlogentry_project_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCursor",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "tenant",
                        "client_id",
                        "project_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("project_id", models.UUIDField()),
                ("last_applied_mutation_number", models.BigIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_cursors",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=GRANT_THE_APPLICATION_ITS_ADVANCE,
            reverse_sql=REVOKE_THE_APPLICATION_ITS_ADVANCE,
        ),
        migrations.RunSQL(sql=ENABLE_THE_WALL, reverse_sql=DISABLE_THE_WALL),
    ]
