# Generated by Django 5.2.16 on 2026-09-18 16:31
#
# The per-operation verdict of ADR-0014: the cursor renamed with what it now counts (decision 5),
# the two columns a refused operation is retained under, and the constraint that pairs them
# (decision 3).
#
# Wholly the autodetector's. The one-off default on the verdict is not preserved on the field,
# because every entry this schema already held was written by a flush that was all-or-nothing and
# therefore applied.

import mapsift.sync.envelope
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membership_membership_by_user_for_login"),
        ("sync", "0003_clientcursor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientcursor",
            old_name="last_applied_mutation_number",
            new_name="last_decided_mutation_number",
        ),
        migrations.AddField(
            model_name="operationlogentry",
            name="refusal_reason",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="operationlogentry",
            name="verdict",
            field=models.CharField(default="applied", max_length=32),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="operationlogentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("refusal_reason__isnull", False),
                        ("verdict", mapsift.sync.envelope.Verdict["refused"]),
                    ),
                    models.Q(
                        models.Q(
                            ("verdict", mapsift.sync.envelope.Verdict["refused"]),
                            _negated=True,
                        ),
                        ("refusal_reason__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="a_reason_exactly_where_the_verdict_refuses",
            ),
        ),
    ]
